apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: meryembounit/devops:latest  # Replace with your Docker image
        ports:
        - containerPort: 5000  # Flask app listens on port 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: NodePort
  ports:
  - port: 5000  # Service port
    targetPort: 5000  # Container port
    nodePort: 30000  # External access port (optional)
  selector:
    app: flask-app